import Head from "next/head";
import Header from "../src/components/Header/Header";
import LandingPage from "../src/components/LandingPage/LandingPage";

const Home = () => {
  return (
    <>
      <Head>
        <title>CUYTEAMS!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <LandingPage />
      </>
    </>
  );
};

export default Home;
