import Head from "next/head";
import LandingPage from "../src/components/LandingPage/LandingPage";

const Home = () => {
  console.log(new Date());
  return (
    <div>
      <Head>
        <title>CUYTEAMS!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
    </div>
  );
};

export default Home;
